name: Build sing-box Binary

on:
  push:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    name: Build sing-box-${{ matrix.sing-box_branch }}-${{ matrix.nickname }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - nickname: "linux-amd64v4-glibc-server"
            sing-box_branch: "testing"
            extra: "GOAMD64=v4"
            tag: "with_quic with_utls with_acme tfogo_checklinkname0 badlinkname"
          - nickname: "linux-amd64v3-glibc-server"
            sing-box_branch: "testing"
            extra: "GOAMD64=v3"
            tag: "with_quic with_utls with_acme tfogo_checklinkname0 badlinkname"
          - nickname: "linux-amd64v2-glibc-server"
            sing-box_branch: "testing"
            extra: "GOAMD64=v2"
            tag: "with_quic with_utls with_acme tfogo_checklinkname0 badlinkname"
          - nickname: "linux-amd64v1-glibc-server"
            sing-box_branch: "testing"
            extra: "GOAMD64=v1"
            tag: "with_quic with_utls with_acme tfogo_checklinkname0 badlinkname"
          - nickname: "linux-amd64-glibc-server"
            sing-box_branch: "testing"
            extra: ""
            tag: "with_quic with_utls with_acme tfogo_checklinkname0 badlinkname"
          - nickname: "linux-amd64-musl-server"
            sing-box_branch: "testing"
            extra: "CGO_ENABLED=0"
            tag: "with_quic with_utls with_acme tfogo_checklinkname0 badlinkname"
          - nickname: "linux-arm64-musl-server"
            sing-box_branch: "testing"
            extra: "CGO_ENABLED=0 GOARCH=arm64"
            tag: "with_quic with_utls with_acme tfogo_checklinkname0 badlinkname"
          - nickname: "linux-amd64v4-glibc-v2rayN"
            sing-box_branch: "stable"
            extra: "GOAMD64=v4"
            tag: "with_gvisor with_quic with_utls with_wireguard with_clash_api tfogo_checklinkname0 badlinkname"
          - nickname: "linux-amd64v3-glibc-v2rayN"
            sing-box_branch: "stable"
            extra: "GOAMD64=v3"
            tag: "with_gvisor with_quic with_utls with_wireguard with_clash_api tfogo_checklinkname0 badlinkname"
          - nickname: "linux-amd64v2-glibc-v2rayN"
            sing-box_branch: "stable"
            extra: "GOAMD64=v2"
            tag: "with_gvisor with_quic with_utls with_wireguard with_clash_api tfogo_checklinkname0 badlinkname"
          - nickname: "linux-amd64v1-glibc-v2rayN"
            sing-box_branch: "stable"
            extra: "GOAMD64=v1"
            tag: "with_gvisor with_quic with_utls with_wireguard with_clash_api tfogo_checklinkname0 badlinkname"
          - nickname: "linux-amd64-glibc-v2rayN"
            sing-box_branch: "stable"
            extra: ""
            tag: "with_gvisor with_quic with_utls with_wireguard with_clash_api tfogo_checklinkname0 badlinkname"
          - nickname: "darwin-arm64-v2rayN"
            sing-box_branch: "stable"
            extra: "GOOS=darwin GOARCH=arm64"
            tag: "with_gvisor with_quic with_utls with_wireguard with_clash_api tfogo_checklinkname0 badlinkname"
          - nickname: "windows-amd64-v2rayN.exe"
            sing-box_branch: "stable"
            extra: "GOOS=windows"
            tag: "with_gvisor with_quic with_utls with_wireguard with_clash_api tfogo_checklinkname0 badlinkname"

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          path: useless/
    
      - name: Clone sing-box Source Code
        shell: bash
        run: |
          git clone https://github.com/SagerNet/sing-box.git
          cd sing-box
          git checkout ${{ matrix.sing-box_branch }}
          git pull
          git fetch --tags --force

      - name: Set up Go
        uses: actions/setup-go@main
        with:
          go-version: 'stable'
          
      - name: Build!
        shell: bash
        run: |
          cd sing-box
          sed -i 's/GOOS=$(GOHOSTOS) GOARCH=$(GOHOSTARCH) go run/GOOS=$(GOHOSTOS) GOARCH=$(GOHOSTARCH) GOAMD64= go run/' Makefile
          VERSION=$(go run github.com/sagernet/sing-box/cmd/internal/read_tag@latest)
          ${{ matrix.extra }} TAGS="${{ matrix.tag }}" VERSION="$VERSION" make -j$(nproc)
          mv sing-box* "sing-box-${{ matrix.sing-box_branch}}-${{ matrix.nickname }}"

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: sing-box
          files: sing-box/sing-box-${{ matrix.sing-box_branch}}-${{ matrix.nickname }}
          body: |
            # This release created by GitHub Actions
            - Make sing-box with some tags i need
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
