name: Automatically Build sing-box

on:
  schedule:
    - cron: '0 */4 * * *'
  push:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  Binary:
    name: Build sing-box-${{ matrix.nickname }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - nickname: "linux-amd64v4-glibc-server"
            sing-box_branch: "testing"
            extra: "GOAMD64=v4"
            tag: "with_quic with_utls with_acme tfogo_checklinkname0 badlinkname"
          - nickname: "linux-amd64v3-glibc-server"
            sing-box_branch: "testing"
            extra: "GOAMD64=v3"
            tag: "with_quic with_utls with_acme tfogo_checklinkname0 badlinkname"
          - nickname: "linux-amd64v2-glibc-server"
            sing-box_branch: "testing"
            extra: "GOAMD64=v2"
            tag: "with_quic with_utls with_acme tfogo_checklinkname0 badlinkname"
          - nickname: "linux-amd64v1-glibc-server"
            sing-box_branch: "testing"
            extra: "GOAMD64=v1"
            tag: "with_quic with_utls with_acme tfogo_checklinkname0 badlinkname"
          - nickname: "linux-amd64-glibc-server"
            sing-box_branch: "testing"
            extra: ""
            tag: "with_quic with_utls with_acme tfogo_checklinkname0 badlinkname"
          - nickname: "linux-amd64-musl-server"
            sing-box_branch: "testing"
            extra: "CGO_ENABLED=0"
            tag: "with_quic with_utls with_acme tfogo_checklinkname0 badlinkname"
          - nickname: "linux-arm64-musl-server"
            sing-box_branch: "testing"
            extra: "CGO_ENABLED=0 GOARCH=arm64"
            tag: "with_quic with_utls with_acme tfogo_checklinkname0 badlinkname"
          - nickname: "linux-amd64v4-glibc-v2rayN"
            sing-box_branch: "stable"
            extra: "GOAMD64=v4"
            tag: "with_quic with_wireguard with_utls with_clash_api with_gvisor tfogo_checklinkname0 badlinkname"
          - nickname: "linux-amd64v3-glibc-v2rayN"
            sing-box_branch: "stable"
            extra: "GOAMD64=v3"
            tag: "with_quic with_wireguard with_utls with_clash_api with_gvisor tfogo_checklinkname0 badlinkname"
          - nickname: "linux-amd64v2-glibc-v2rayN"
            sing-box_branch: "stable"
            extra: "GOAMD64=v2"
            tag: "with_quic with_wireguard with_utls with_clash_api with_gvisor tfogo_checklinkname0 badlinkname"
          - nickname: "linux-amd64v1-glibc-v2rayN"
            sing-box_branch: "stable"
            extra: "GOAMD64=v1"
            tag: "with_quic with_wireguard with_utls with_clash_api with_gvisor tfogo_checklinkname0 badlinkname"
          - nickname: "linux-amd64-glibc-v2rayN"
            sing-box_branch: "stable"
            extra: ""
            tag: "with_quic with_wireguard with_utls with_clash_api with_gvisor tfogo_checklinkname0 badlinkname"
          - nickname: "darwin-arm64-v2rayN"
            sing-box_branch: "stable"
            extra: "GOOS=darwin GOARCH=arm64"
            tag: "with_quic with_wireguard with_utls with_clash_api with_gvisor tfogo_checklinkname0 badlinkname"
          - nickname: "windows-amd64-v2rayN.exe"
            sing-box_branch: "stable"
            extra: "GOOS=windows"
            tag: "with_quic with_wireguard with_utls with_clash_api with_gvisor tfogo_checklinkname0 badlinkname"

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          path: useless/
    
      - name: Clone sing-box Source Code
        shell: bash
        run: |
          git clone https://github.com/SagerNet/sing-box.git
          cd sing-box
          git checkout ${{ matrix.sing-box_branch }}
          git pull
          git fetch --tags --force

      - name: Set up Go
        uses: actions/setup-go@main
        with:
          go-version: 'stable'
          
      - name: Build!
        shell: bash
        run: |
          cd sing-box
          go mod tidy
          go get -u ./...
          go fmt ./...
          sed -i 's/GOOS=$(GOHOSTOS) GOARCH=$(GOHOSTARCH) go run/GOOS=$(GOHOSTOS) GOARCH=$(GOHOSTARCH) GOAMD64= go run/' ./Makefile
          VERSION=$(go run github.com/sagernet/sing-box/cmd/internal/read_tag@latest)
          ${{ matrix.extra }} TAGS="${{ matrix.tag }}" VERSION=$VERSION make -j$(nproc)
          mv sing-box* sing-box-${{ matrix.sing-box_branch}}-${{ matrix.nickname }}

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: sing-box
          files: sing-box/sing-box-${{ matrix.sing-box_branch }}-${{ matrix.nickname }}
          body: |
            # 🚀 Make sing-box
            > with some tag i need and performance +++++
            # ⚠️ Filename rule
            > sing-box-branch-os-arch(optimize)-libc(only linux)-uses
            >
            > But navieproxy can't run because i no need this.
            # 🪞 Mirror
            [By myself](https://867678.xyz/doc/Mirror)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  OpenWrt:
    name: Build sing-box-${{ matrix.nickname }}
    needs: Binary
    runs-on: ubuntu-latest
    env:
      project_name: "luci-app-ezsgx"
    strategy:
      fail-fast: false
      matrix:
        include:
          - nickname: "amd64-musl-server"
            patch_arch: "x86_64"
            sdk_arch: "x86-64"
          - nickname: "arm64-musl-server"
            patch_arch: "aarch64_generic"
            sdk_arch: "rockchip-armv8"
          - nickname: "arm64-musl-server"
            patch_arch: "aarch64_cortex-a53"
            sdk_arch: "mediatek-filogic"

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          path: useless/
        
      - name: Preparing build environment
        uses: moaeiou/moaeiou/actions/build-env@main

      - name: Prepare SDK
        uses: moaeiou/moaeiou/actions/prepare-sdk@main
        id: sdk
        with:
          sdk_arch: ${{ matrix.sdk_arch }}
      
      - name: Prepare before complie
        shell: bash
        run: |
          cd ${{ steps.sdk.outputs.sdk_dir }}/package
          git clone https://github.com/morouter/luci-app-ezsgx.git
          cd ${{ env.project_name }}
          git checkout sing-box-op
          git pull
          cd root/usr/bin/
          rm DONOTREMOVE
          wget -O sing-box https://github.com/morouter/luci-app-ezsgx/releases/download/sing-box/sing-box-testing-linux-${{ matrix.nickname }}
          chmod +x ./sing-box
          cd ../../../
          if [ "${{ matrix.patch_arch }}" != "x86_64" ]; then
          sed -i 's/x86_64/${{ matrix.patch_arch }}/g' ./Makefile
          fi

      - name: Build!
        shell: bash
        run: |
          cd ${{ steps.sdk.outputs.sdk_dir }}
          make package/${{ env.project_name }}/compile V=s -j$(nproc)
          cd $GITHUB_WORKSPACE
          shopt -s globstar
          mv ${{ steps.sdk.outputs.sdk_dir }}/bin/packages/**/sing-box*.apk ${{ github.workspace }}/sing-box-${{ matrix.patch_arch }}.apk

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: sing-box-openwrt
          files: ${{ github.workspace }}/sing-box-${{ matrix.patch_arch }}.apk
          body: |
            # 🚀 sing-box OpenWrt
            > with some tag i need and performance +++++
            # 💬 Filename rule
            > sing-box-patch-arch
            # ⚠️ WARNING
            > If you not have this depends, else it can't work
            >
            > Usually, this be auto install. but if auto not work , you aslo can be do it yourself.
            ```
            apk add ca-bundle kmod-inet-diag kmod-tun firewall4 kmod-nft-queue
            ```
            # 🪞 Mirror
            [By myself](https://867678.xyz/doc/Mirror)
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 