name: Manuel Build sing-box for OpenWrt

on:
  workflow_run:
    workflows: ["Automanticly Build sing-box"]
    types:
      - completed
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    name: Build sing-box-${{ matrix.patch_arch }}
    runs-on: ubuntu-latest
    env:
      project_name: "luci-app-ezsgx"
    strategy:
      fail-fast: false
      matrix:
        include:
          - sing-box_nickname: "amd64-musl-server"
            patch_arch: "x86_64"
            sdk_name: "openwrt-sdk-x86-64_gcc-14.3.0_musl.Linux-x86_64"
          - sing-box_nickname: "arm64-musl-server"
            patch_arch: "aarch64_generic"
            sdk_name: "openwrt-sdk-rockchip-armv8_gcc-14.3.0_musl.Linux-x86_64"
          - sing-box_nickname: "arm64-musl-server"
            patch_arch: "aarch64_cortex-a53"
            sdk_name: "openwrt-sdk-mediatek-filogic_gcc-14.3.0_musl.Linux-x86_64"

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          path: useless/
        
      - name: Preparing build environment
        uses: mokanove/mokanove/actions/build-env@main

      - name: Prepare SDK
        uses: mokanove/mokanove/actions/prepare-sdk@main
        with:
          sdk_name: ${{ matrix.sdk_name }}
      
      - name: Prepare before complie
        shell: bash
        run: |
          cd ${{ matrix.sdk_name }}/package
          git clone https://github.com/mokanove/luci-app-ezsgx.git
          cd ${{ env.project_name }}
          git checkout openwrt
          git pull
          cd root/usr/bin/
          rm DONOTREMOVE
          wget -O sing-box https://github.com/mokanove/luci-app-ezsgx/releases/download/sing-box/sing-box-testing-linux-${{ matrix.sing-box_nickname }}
          chmod +x ./sing-box
          cd ../../../
          if [ "${{ matrix.patch_arch }}" != "x86_64" ]; then
          sed -i 's/x86_64/${{ matrix.patch_arch }}/g' ./Makefile
          fi
          sed -i 's/GOOS=$(GOHOSTOS) GOARCH=$(GOHOSTARCH) go run/GOOS=$(GOHOSTOS) GOARCH=$(GOHOSTARCH) GOAMD64= go run/' Makefile
          SINGBOX_VERSION=$(go run github.com/sagernet/sing-box/cmd/internal/read_tag@latest)
          sed -i 's/VERCION/$SINGBOX_VERSION/g' ./Makefile

      - name: Build!
        shell: bash
        run: |
          cd ${{ matrix.sdk_name }}
          make package/${{ env.project_name }}/compile V=s j$(nproc)
          cd $GITHUB_WORKSPACE
          mv ${{ matrix.sdk_name }}/bin/packages/*/base/sing-box*.apk $GITHUB_WORKSPACE/sing-box-${{ matrix.patch_arch }}.apk

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: sing-box-openwrt
          files: ${{ github.workspace }}/sing-box-${{ matrix.patch_arch }}.apk
          body: |
            # 🚀 sing-box OpenWrt
            > with some tag i need and performance +++++
            # ⚠️ Filename rule
            > sing-box-patch-arch
            >
            > And you must be install this depends, else it can't work
            ```
            apk add ca-bundle kmod-inet-diag kmod-tun firewall4 kmod-nft-queue
            ```
            # 🪞 Mirror
            [By myself](https://867678.xyz/doc/Mirror)
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 